// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuskeitsApi.Models;

#nullable disable

namespace SuskeitsApi.Migrations
{
    [DbContext(typeof(SuskeitsDbContext))]
    partial class SuskeitsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SuskeitsApi.Models.Kasutaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Eesnimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kasutajanimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Parool")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Perenimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kasutajad");
                });

            modelBuilder.Entity("SuskeitsApi.Models.Toode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KasutajaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("KasutajaId");

                    b.ToTable("Tooted");
                });

            modelBuilder.Entity("SuskeitsApi.Models.Toode", b =>
                {
                    b.HasOne("SuskeitsApi.Models.Kasutaja", "Kasutaja")
                        .WithMany("Tooted")
                        .HasForeignKey("KasutajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kasutaja");
                });

            modelBuilder.Entity("SuskeitsApi.Models.Kasutaja", b =>
                {
                    b.Navigation("Tooted");
                });
#pragma warning restore 612, 618
        }
    }
}
